services:
  - type: web
    name: online-students-clearance-system
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn core.wsgi:application"
