"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8woy^^+*w%n4t5!oow51wnoneh_uqn^2-gtm)-fx2==3))8*k#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# === LINK YAKO YA RENDER IMEONGEZWA HAPA KUTATUA KILE KOSA ===
ALLOWED_HOSTS = [
    'online-students-clearance-system.onrender.com',
    '127.0.0.1',
    'localhost',
    '*'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # === JINA LA APP YAKO ===
    'clearance_app', 
    
    # === MFUMO WA ULINZI WA ACCOUNT LOCKOUT ===
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # === AXES MIDDLEWARE (LAZIMA IKAE CHINI KABISA YA AUTH MIDDLEWARE) ===
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # === BINILISHI KWA AJILI YA HTML TEMPLATES ===
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# Mipangilio ya SQLite (Inatumia lile faili la db.sqlite3 moja kwa moja kuzuia migogoro ya matoleo)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# TIME ZONE YA NYUMBANI TANZANIA
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Muundo sahihi wa folder la static kwa ajili ya CSS na JS zenu
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Mipangilio ya Login na Redirects (Mfumo kuwaka kwa pamoja)
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard_redirect'
LOGOUT_REDIRECT_URL = 'login'

# Inazuia onyo la models.W042 kwenye Terminal
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
#                 MIPANGILIO YA ULINZI (NON-FUNCTIONAL REQUIREMENTS)
# ==============================================================================
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # Inakagua majaribio ya login kwanza kabla ya mfumo wa kawaida
    'django.contrib.auth.backends.ModelBackend',
]

# Mtu akikosea nenosiri mara 3 mfululizo, anafungiwa katakata
AXES_FAILURE_LIMIT = 3

# Muda wa kufungiwa kwa masaa 48 kama requirement inavyotaka
AXES_COOLOFF_TIME = 48

# Inamfungia mtumiaji kulingana na mchanganyiko wa Username yake na IP ya kompyuta yake
AXES_LOCKOUT_BY_COMBINATION = True

# Ukurasa maalum wa kumwambia amefungiwa kwa masaa 48
AXES_LOCKOUT_TEMPLATE = 'lockout.html'